[package]
name = "rust_sphere"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
geo = "0.29"
rayon = "1.10"
glam = "0.29" # Fast 3D math